name: Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential zip curl scons libncurses5-dev git-core gnupg flex bison gperf libxml2-utils libssl-dev libcurl4-openssl-dev liblz4-tool

    - name: Install Repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Sync TWRP Sources
      run: |
        mkdir work && cd work
        repo init --u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-14
        repo sync -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Add Device Tree
      run: |
        cd work
        git clone ${{ github.server_url }}/${{ github.repository }} device/tecno/li9

    - name: Build Recovery
      run: |
        cd work
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch twrp_li9-eng
        mka recoveryimage -j$(nproc --all)

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-Pova6Pro
        path: work/out/target/product/li9/recovery.img
